### ISSUE TITLE
Example "larger.hs" doesn't compile in stack lts-12.21

### ISSUE THREAD

**Issue by proegssilb** [myfreeweb/magicbane#23]
I haven't investigated this a lot yet, but in my app, it looks like trying to use the env var-driven config is a recipe for build errors. I'm following along with the `larger.hs` example. Removing the typeclass instance for `DefConfig` results in a missing instance, having `DefConfig` but no `FromEnv` is fine (until you want to parse config from env vars), and having `DefConfig`/`FromEnv` without a definition for `fromEnv` doesn't change the behavior.

I have not tried multiple LTS resolvers yet. If there's a particular resolver I should use, I'm open to suggestions. I also have not double-checked the official library's documentation. Even if there's relevant info in upstream documentation, we should work on making sure the examples compile for reasonably recent stack setups.

Here's a sample of what happens when compiling the example `larger.hs` straight from this repository in my project (As close as I can easily get to a minimal, complete, verifiable example):

```
user@host ~/project $ stack ghc larger.hs 
[1 of 1] Compiling Main             ( larger.hs, larger.o )

larger.hs:18:13: error:
    • Overlapping instances for DefConfig LargeAppConf
        arising from a use of ‘gFromEnvCustom’
      Matching instances:
        instance Default α => DefConfig α -- Defined in ‘Magicbane’
        instance DefConfig LargeAppConf -- Defined at larger.hs:12:10
    • In the expression:
        gFromEnvCustom
          Option {dropPrefixCount = 0, customPrefix = "LARGEAPP"}
      In an equation for ‘fromEnv’:
          fromEnv
            = gFromEnvCustom
                Option {dropPrefixCount = 0, customPrefix = "LARGEAPP"}
      In the instance declaration for ‘FromEnv LargeAppConf’
   |
18 |   fromEnv = gFromEnvCustom Option { dropPrefixCount = 0, customPrefix = "LARGEAPP" }
   |
```

I'm familiar with basic Haskell, and very new to Magicbane (and all of its dependencies), but let me know if there's anything else I can do to help with this.

**Comment by valpackett** [comment]
You're on magicbane 0.3.0, which is old. Unfortunately, magicbane is not currently in Stackage. You have to use extra-deps:

```
extra-deps:
  - magicbane-0.4.0
  - wai-middleware-metrics-0.2.4
  - monad-metrics-0.2.1.2
  - rio-orphans-0.1.1.0
  - ekg-wai-0.1.0.3
  - ekg-json-0.1.0.6
```

(these other dependencies are required with the latest nightly, maybe you need less/more — try just magicbane and see what stack tells you.)

**Comment by proegssilb** [comment]
For now, just add the proper version of magicbane as an extra dep did the trick. I'll have to keep track of that list in case I bump into something later. Out of curiosity, why was magicbane removed from stackage? Is there something I should be working on/looking into in order to get magicbane back into stackage?

**Comment by valpackett** [comment]
Looks like there's some problem with the `ekg` dependency:

`magicbane < 0 # via ekg-wai`

`ekg-wai < 0 # via ekg-json`

`ekg-json < 0 # via aeson-1.4.0.0`

**Comment by proegssilb** [comment]
Hmm, OK. That sounds like a lot of follow-up. As nice as it'd be to get magicbane back into stackage, I'm going to try to focus on the app I'm working on for now. Thanks for your help.

**Comment by valpackett** [comment]
Yeah, I hope someone will fix ekg. Or I can drop it, it's not like anyone actually measures anything with metrics, right? :D
