### ISSUE TITLE
Examples won't build in stackage LTS-9.0

### ISSUE THREAD

**Issue by erochest** [myfreeweb/magicbane#4]
Hi,

Trying to build the examples in [stackage LTS-9.0](https://www.stackage.org/lts-9.0) gives this error (for `tiny.hs`, but I've also seen this with `larger.hs` and an app I was working on):

```bash
> stack build
magicbane-examples-0.0.0: build (exe)
Preprocessing executable 'tiny' for magicbane-examples-0.0.0...
[1 of 1] Compiling Main             ( tiny.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/tiny/tiny-tmp/Main.o )

/Users/ericrochester/tmp/magicbane/examples/tiny.hs:17:16: error:
    • Couldn't match type ‘Handler’ with ‘ExceptT ServantErr IO’
        arising from a functional dependency between:
          constraint ‘servant-0.11:Servant.Utils.Enter.Enter
                        (BasicApp Text)
                        (MagicbaneApp BasicContext)
                        (ExceptT ServantErr IO)
                        (Handler Text)’
            arising from a use of ‘magicbaneApp’
          instance ‘servant-0.11:Servant.Utils.Enter.Enter (m a) m n (n a)’
            at <no location info>
    • In the second argument of ‘($)’, namely
        ‘magicbaneApp exampleAPI EmptyContext ctx hello’
      In a stmt of a 'do' block:
        defWaiMain $ magicbaneApp exampleAPI EmptyContext ctx hello
      In the expression:
        do { ctx <- newBasicContext;
             defWaiMain $ magicbaneApp exampleAPI EmptyContext ctx hello }

--  While building package magicbane-examples-0.0.0 using:
      /Users/ericrochester/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build exe:tiny --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

For reference, `package.yaml` looks like:

```yaml
name: magicbane-examples
dependencies:
  - base >=4.8.0.0 && <5
  - magicbane
executables:
  tiny:
    main: tiny.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
```

Should I be using magicbane from master branch instead of the release?

Thanks,
Eric

**Comment by valpackett** [comment]
Hi!

Nothing substantial changed on master since the 0.1.1 release, only https://github.com/myfreeweb/magicbane/commit/55ce89dd93cfc84e7b79599327ad644dde6e8c74.

Stick with LTS 8.x for now, I'll look into this today.

**Comment by erochest** [comment]
No rush. I suspect that something may have changed in one of the dependencies.

If you don't get to it, no problem. I may dig into it later this week myself.

**Comment by valpackett** [comment]
Oh, so they've introduced a `newtype` wrapper called `Handler` around `ExceptT ServantErr IO`, for whatever reason.

**Comment by erochest** [comment]
Ah, nice. That would do it. I wonder what the reasoning was.

Thank you for responding so quickly!
